# https://docs.travis-ci.com/user/build-config-imports/

version: ~> 1

# main
import:
- source: creative-commoners/silverstripe-framework:travis-shared/main.yml@pulls/4/shared-travis-config
  mode: deep_merge_append

# behat
import:
- source: creative-commoners/silverstripe-framework:travis-shared/behat.yml@pulls/4/shared-travis-config
  mode: deep_merge_prepend

#- source: travis-import.yml
#  mode: deep_merge_append
