---
Name: assetadmin
---
SilverStripe\Assets\File:
  extensions:
    - SilverStripe\AssetAdmin\Controller\AssetAdminFile
SilverStripe\Admin\LeftAndMain:
  extensions:
    - SilverStripe\AssetAdmin\Controller\AssetAdminFieldsExtension
---
Name: assetadminfield
After:
  - '#coreassetfield'
---
SilverStripe\Core\Injector\Injector:
  SilverStripe\Forms\FileHandleField:
    class: SilverStripe\AssetAdmin\Forms\UploadField
---
Name: assetadmincampaigns
Only:
  moduleexists: 'silverstripe/campaign-admin'
After:
  - '#cmscampaigns'
---
SilverStripe\AssetAdmin\Forms\FileFormFactory:
  extensions:
    - 'SilverStripe\AssetAdmin\Extensions\CampaignAdminExtension'
SilverStripe\CampaignAdmin\CampaignAdmin:
  placeholder_group_classes:
    - 'SilverStripe\Assets\File'
---
Name: assetadminmodals
---
SilverStripe\Admin\ModalController:
  extensions:
    - SilverStripe\AssetAdmin\Extensions\RemoteFileModalExtension
